# Generated by Django 6.0.2 on 2026-02-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('chronology', '0002_alter_chronology_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='chronology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='chronology.chronology'),
        ),
    ]
