# Generated by Django 6.0.2 on 2026-02-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_initial_event'),
        ('event', '0004_event_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='initial_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_branch', to='event.event'),
        ),
    ]
