# Generated by Django 6.0.2 on 2026-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronology',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chronology',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
