# Generated by Django 6.0.2 on 2026-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actors',
            field=models.ManyToManyField(related_name='events', to='event.actor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_label',
            field=models.CharField(max_length=255),
        ),
    ]
