# Generated by Django 6.0.2 on 2026-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_actors_alter_event_time_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.actor'),
        ),
    ]
